server.port: 8761

eureka:
  instance:
    health-check-url-path: "/actuator/health"
    status-page-url-path: "/actuator/info"
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false