-- CREATE DATABASE IF NOT EXISTS backend;

CREATE TABLE IF NOT EXISTS product_reviews (
	review_id int PRIMARY KEY AUTO_INCREMENT,
	product_id VARCHAR(7) NOT NULL,
	review_score INT NOT NULL,
	review_comment TEXT NOT NULL,
	createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updateAt TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);